"""Stratified pilot-corpus builder for the audit.

Wraps the five existing generator CLIs without modifying them. Questions
generated through this module are tagged `audit_pilot_v1` so every downstream
agent can filter the corpus by tag.

Design notes:
- We call each strategy with a bounded `--count` per domain. The strategy
  itself picks difficulty/cognitive dim/question type from its own logic.
- After each call, we tag the newly-created rows for that `generation_method`
  so stage 2 agents know which corpus to read.
- `gold_sheet` export produces a CSV the reviewer fills offline; `import`
  writes it back into `audit_gold_labels`.
"""

from __future__ import annotations

import csv
import os
import random
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Iterable

import click
from loguru import logger

from src.generators._question_db import (
    CORPUS_BUILD_SINCE_ENV_VAR,
    CORPUS_TARGET_ENV_VAR,
    STRATEGY_TARGET_ENV_VAR,
    set_corpus_target,
)
from src.qa._findings import upsert_gold_label
from src.utils.db import get_pg

STRATEGY_MODULES = {
    "template": "template_generator",
    "fact_to_question": "fact_to_question",
    "comparative": "comparative_generator",
    "scenario_synthesis": "scenario_generator",
    "distractor_mining": "distractor_miner",
}

DOMAINS = [
    "wine_regions",
    "winemaking",
    "viticulture",
    "grape_varieties",
    "wine_business",
    "producers",
]

LLM_STRATEGIES = {"fact_to_question", "comparative", "scenario_synthesis", "distractor_mining"}

GENERATORS = ["claude", "chatgpt", "gemini", "llama", "qwen"]


# ─── Helpers ──────────────────────────────────────────────────────────────────


def _tag_rows(
    *,
    generation_method: str,
    since: datetime,
    limit: int,
    tag: str,
) -> int:
    """Add `tag` to the tags[] of the newest `limit` questions generated by
    `generation_method` after `since`. Returns rows updated."""
    conn = get_pg()
    cur = conn.cursor()
    cur.execute(
        """
        WITH candidates AS (
            SELECT q.id
            FROM   questions q
            JOIN   generation_metadata gm ON gm.question_id = q.id
            WHERE  gm.generation_method = %s
              AND  q.created_at >= %s
            ORDER BY q.created_at
            LIMIT  %s
        )
        UPDATE questions q
           SET tags = array_append(
                   COALESCE(array_remove(q.tags, %s), '{}'::text[]),
                   %s)
         FROM  candidates c
         WHERE q.id = c.id
        """,
        (generation_method, since, limit, tag, tag),
    )
    updated = cur.rowcount
    conn.commit()
    return updated


def _existing_corpus_count(tag: str) -> dict[str, int]:
    conn = get_pg()
    cur = conn.cursor()
    cur.execute(
        """
        SELECT gm.generation_method, count(*) AS cnt
        FROM   questions q
        JOIN   generation_metadata gm ON gm.question_id = q.id
        WHERE  %s = ANY(q.tags)
        GROUP  BY gm.generation_method
        """,
        (tag,),
    )
    return {row["generation_method"]: row["cnt"] for row in cur.fetchall()}


def _run_generator(
    *,
    module: str,
    domain: str,
    count: int,
    generator: str | None = None,
    difficulty: int | None = None,
    per_country_cap: float | None = None,
) -> bool:
    args = [
        sys.executable,
        "-m",
        f"src.generators.{module}",
        "--domain",
        domain,
        "--count",
        str(count),
    ]
    if generator:
        args += ["--generator", generator]
    if difficulty:
        args += ["--difficulty", str(difficulty)]
    if per_country_cap is not None:
        # Phase 2g.8 fix: previously per_country_cap was plumbed only into
        # the sampler functions; the audit-pilot orchestrator never passed
        # it through to the strategy subprocesses, so audit_pilot_v6 ran
        # with NO country cap (D3 ratio = 4.52). All 5 strategy CLIs
        # accept --per-country-cap as of Phase 2g.8.
        args += ["--per-country-cap", str(per_country_cap)]
    logger.info("corpus: running {}", " ".join(args[2:]))
    res = subprocess.run(args)
    if res.returncode != 0:
        logger.error("corpus: generator exited non-zero: {}", " ".join(args))
        return False
    return True


# ─── Build ────────────────────────────────────────────────────────────────────


def build_pilot_corpus(
    *,
    tag: str = "audit_pilot_v1",
    per_strategy: int = 120,
    seed: int = 42,
    skip_strategies: Iterable[str] = (),
    per_country_cap: float | None = None,
) -> dict:
    """Generate ~`per_strategy` questions for each strategy and tag them.

    Total target = 5 × per_strategy (≈600 for MVA).
    Per-strategy breakdown is round-robin across domains (and generators
    for LLM strategies) so we get reasonable coverage without micro-managing
    difficulty/cognitive cells inside each call.

    Args:
        per_country_cap: Phase 2g.8. Forwarded to every strategy subprocess
            via ``--per-country-cap``. Set to a fraction in (0, 1] to enforce
            a per-call country cap on the sampler (Team ε D3-fix v3); ``None``
            disables. Audit pilots should typically pass 0.10.
    """
    random.seed(seed)
    started = datetime.now()

    counts_before = _existing_corpus_count(tag)
    logger.info("corpus: existing rows with tag {} = {}", tag, counts_before)

    # Phase 2g.8: scope the closed-book quota cap to this pilot's size, not the
    # 10k full-run default. Without this, a 600-Q pilot's cap is 2500 (i.e.
    # effectively no cap), which let v6 leak 158 closed-book relabels on a
    # 264-Q corpus instead of the documented ceil(264 × 0.25) = 66. The
    # `try/finally` ensures the override is cleared even if a strategy raises,
    # so subsequent processes (full-gen runs, tests) see clean state.
    #
    # Phase 2g.9 (audit #7 follow-up): in addition to the in-process module-
    # global, also export an env var so child subprocesses spawned by
    # `_run_generator` resolve the same scoped cap. The module-global alone
    # only works for in-process callers; v7 ran with the default 10k cap and
    # accumulated 172 closed-book relabels on a 242-Q corpus.
    target_size = per_strategy * len(STRATEGY_MODULES)
    set_corpus_target(target_size)
    prev_env_target = os.environ.get(CORPUS_TARGET_ENV_VAR)
    os.environ[CORPUS_TARGET_ENV_VAR] = str(target_size)
    # Phase 2g.9 hotfix: scope the closed-book count to questions created
    # during this build only. Without this, the global query in
    # `count_closed_book_solvable()` totals every historical pilot's
    # cb-tagged questions; v8's first launch saw 427/50 immediately because
    # v5+v6+v7 had already accumulated 427 cb-tagged questions in the DB.
    prev_env_since = os.environ.get(CORPUS_BUILD_SINCE_ENV_VAR)
    os.environ[CORPUS_BUILD_SINCE_ENV_VAR] = started.isoformat()
    # Phase 2g.10: per-strategy closed-book budget. Each strategy gets its
    # own ceil(per_strategy × 0.25) slot count, counted by generation_method,
    # so the first strategy in build order can't monopolise the corpus-wide
    # cap and starve later strategies. The corpus-level env var stays set so
    # callers without a generation_method (or without the per-strategy var)
    # still fall back to the corpus cap.
    prev_env_strategy = os.environ.get(STRATEGY_TARGET_ENV_VAR)
    os.environ[STRATEGY_TARGET_ENV_VAR] = str(per_strategy)
    logger.info(
        "corpus: set closed-book quota target to {} (per-pilot 25% cap), "
        "per-strategy budget {} (per-strategy 25% cap = {}), "
        "scoped to questions created since {}",
        target_size, per_strategy,
        (per_strategy * 25 + 99) // 100,
        started.isoformat(),
    )

    results: dict[str, dict] = {}
    try:
        for strategy, module in STRATEGY_MODULES.items():
            if strategy in skip_strategies:
                logger.info("corpus: skipping {}", strategy)
                continue
            already = counts_before.get(strategy, 0)
            if already >= per_strategy:
                logger.info("corpus: {} already at {}/{}, skipping", strategy, already, per_strategy)
                results[strategy] = {"generated": 0, "tagged": 0, "skipped": True}
                continue
            want = per_strategy - already
            strategy_started = datetime.now()

            # LLM strategies: split want across 5 generators × 6 domains ≈ 4 each for 120
            if strategy in LLM_STRATEGIES:
                per_cell = max(1, want // (len(GENERATORS) * len(DOMAINS)))
                rem = want - per_cell * len(GENERATORS) * len(DOMAINS)
                cells = [(g, d) for g in GENERATORS for d in DOMAINS]
                random.shuffle(cells)
                for g, d in cells:
                    take = per_cell + (1 if rem > 0 else 0)
                    if rem > 0:
                        rem -= 1
                    if take <= 0:
                        continue
                    _run_generator(
                        module=module, domain=d, count=take, generator=g,
                        per_country_cap=per_country_cap,
                    )
            else:
                per_cell = max(1, want // len(DOMAINS))
                rem = want - per_cell * len(DOMAINS)
                doms = DOMAINS[:]
                random.shuffle(doms)
                for d in doms:
                    take = per_cell + (1 if rem > 0 else 0)
                    if rem > 0:
                        rem -= 1
                    _run_generator(
                        module=module, domain=d, count=take,
                        per_country_cap=per_country_cap,
                    )

            tagged = _tag_rows(
                generation_method=strategy,
                since=strategy_started,
                limit=want,
                tag=tag,
            )
            results[strategy] = {"generated": want, "tagged": tagged, "skipped": False}
            logger.info("corpus: {} generated={} tagged={}", strategy, want, tagged)
    finally:
        set_corpus_target(None)
        if prev_env_target is None:
            os.environ.pop(CORPUS_TARGET_ENV_VAR, None)
        else:
            os.environ[CORPUS_TARGET_ENV_VAR] = prev_env_target
        if prev_env_since is None:
            os.environ.pop(CORPUS_BUILD_SINCE_ENV_VAR, None)
        else:
            os.environ[CORPUS_BUILD_SINCE_ENV_VAR] = prev_env_since
        if prev_env_strategy is None:
            os.environ.pop(STRATEGY_TARGET_ENV_VAR, None)
        else:
            os.environ[STRATEGY_TARGET_ENV_VAR] = prev_env_strategy

    counts_after = _existing_corpus_count(tag)
    logger.info("corpus: post-build totals = {}", counts_after)
    return {
        "started_at": started.isoformat(),
        "seed": seed,
        "tag": tag,
        "per_strategy": per_strategy,
        "results": results,
        "totals": counts_after,
    }


# ─── Gold sheet ───────────────────────────────────────────────────────────────

GOLD_RUBRICS = [
    "answer_correct",         # the keyed answer is correct given the source
    "distractors_plausible",  # each distractor is plausibly wrong (not trivially eliminable)
    "not_ambiguous",          # only one defensible answer
    "source_faithful",        # question content stays within source fact (semantic)
    "needs_source",           # not solvable purely from general world knowledge
    "no_vague_language",      # no marketing / "acclaimed" / "iconic" etc.
    "difficulty_match",       # difficulty label fits perceived hardness
    "cognitive_match",        # cognitive_dim label fits the cognitive demand
    # v2.3 Team γ — new rubrics that align with narrow LLM-proxy signals.
    # Kept additive so old gold sheets (run #1..#3) still import cleanly.
    "verbatim_copy",          # question/correct-option copies source verbatim (LCS ≥ 0.6)
    "wine_category_leak",     # a distractor's wine category differs from the correct option's
]


def export_gold_sheet(tag: str, out_path: Path, sample_size: int, seed: int) -> int:
    """Sample `sample_size` questions from the corpus and write a CSV for offline review.

    The `source_facts` column contains ALL linked facts joined with `\\n---\\n`
    and prefixed by `[1] ... [2] ... ` so multi-fact strategies (comparative,
    scenario, distractor) can be reviewed against their full evidence base
    (see `docs/GOLD_CALIBRATION_ANALYSIS.md` §3).
    """
    random.seed(seed)
    conn = get_pg()
    cur = conn.cursor()
    # Aggregate ALL linked facts per question. We synthesize a 1-based index
    # via row_number() because question_facts has no explicit ordering column;
    # ordering by fact_id is stable per-question.
    cur.execute(
        """
        WITH ordered_facts AS (
            SELECT
                qf.question_id,
                f.fact_text,
                row_number() OVER (
                    PARTITION BY qf.question_id
                    ORDER BY qf.fact_id
                ) AS fact_order
            FROM question_facts qf
            JOIN facts f ON f.id = qf.fact_id
        )
        SELECT q.id AS uuid, q.question_id, q.domain::text, q.difficulty::text,
               q.cognitive_dim::text, q.question_type::text,
               q.question_text, q.options, q.correct_answer, q.correct_answer_text,
               q.explanation, gm.generator::text, gm.generation_method,
               COALESCE(
                   string_agg(
                       '[' || of.fact_order::text || '] ' || of.fact_text,
                       E'\n---\n'
                       ORDER BY of.fact_order
                   ),
                   ''
               ) AS source_facts
        FROM   questions q
        JOIN   generation_metadata gm ON gm.question_id = q.id
        LEFT   JOIN ordered_facts of ON of.question_id = q.id
        WHERE  %s = ANY(q.tags)
        GROUP  BY q.id, gm.generator, gm.generation_method
        """,
        (tag,),
    )
    rows = cur.fetchall()
    if not rows:
        logger.warning("gold sheet: no rows tagged {}", tag)
        return 0

    # Stratified sample: take ~`sample_size / N_strategies` from each strategy.
    # Within a strategy, sub-stratify across (generator, difficulty) cells so
    # the reviewer doesn't see e.g. all template_only L1 questions clustered
    # at the top. Falls back to random fill when a strategy is short on cells.
    strategy_buckets: dict[str, list[dict]] = {}
    for r in rows:
        strategy_buckets.setdefault(r["generation_method"], []).append(r)

    n_strategies = max(1, len(strategy_buckets))
    per_strategy = max(1, sample_size // n_strategies)

    selected: list[dict] = []
    for method, group in strategy_buckets.items():
        # Build (generator, difficulty) sub-buckets and round-robin pick from
        # them so the per-strategy slice is as balanced as the corpus allows.
        sub: dict[tuple[str, str], list[dict]] = {}
        for r in group:
            key = (r.get("generator") or "template_only", str(r.get("difficulty") or ""))
            sub.setdefault(key, []).append(r)
        for items in sub.values():
            random.shuffle(items)

        chosen: list[dict] = []
        # Round-robin across cells until we hit per_strategy or exhaust the cells.
        keys = sorted(sub.keys())
        random.shuffle(keys)
        while len(chosen) < per_strategy and any(sub[k] for k in keys):
            for k in keys:
                if not sub[k]:
                    continue
                chosen.append(sub[k].pop())
                if len(chosen) >= per_strategy:
                    break
        selected.extend(chosen)
    random.shuffle(selected)
    selected = selected[:sample_size]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        header = [
            "uuid",
            "public_qid",
            "strategy",
            "generator",
            "domain",
            "difficulty",
            "cognitive_dim",
            "question_text",
            "options",
            "correct_answer",
            "source_facts",
        ] + GOLD_RUBRICS + ["notes"]
        writer.writerow(header)
        for r in selected:
            writer.writerow([
                r["uuid"],
                r["question_id"],
                r["generation_method"],
                r["generator"],
                r["domain"],
                r["difficulty"],
                r["cognitive_dim"],
                r["question_text"],
                r["options"],
                r["correct_answer"],
                # Truncated for spreadsheet legibility; full evidence is still
                # present (most multi-fact bundles are well under 2000 chars).
                (r["source_facts"] or "")[:2000],
            ] + [""] * (len(GOLD_RUBRICS) + 1))
    logger.info("gold sheet: wrote {} rows to {}", len(selected), out_path)
    return len(selected)


def import_gold_sheet(csv_path: Path, reviewer: str) -> int:
    """Read a filled gold CSV and upsert into audit_gold_labels.

    Values recognised: 1/0 or y/n or true/false (case-insensitive). Blanks
    are ignored (treated as missing).
    """
    def _norm(val: str) -> bool | None:
        s = val.strip().lower()
        if not s:
            return None
        if s in {"1", "y", "yes", "true", "t"}:
            return True
        if s in {"0", "n", "no", "false", "f"}:
            return False
        return None

    imported = 0
    with csv_path.open(encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            labels: dict[str, bool | None] = {k: _norm(row.get(k, "")) for k in GOLD_RUBRICS}
            if all(v is None for v in labels.values()):
                continue
            qid = row.get("uuid", "").strip()
            if not qid:
                continue
            upsert_gold_label(
                question_id=qid,
                labels=labels,
                reviewer=reviewer,
                notes=row.get("notes", "").strip(),
            )
            imported += 1
    logger.info("gold import: upserted {} rows", imported)
    return imported


# ─── CLI ──────────────────────────────────────────────────────────────────────


@click.group()
def cli() -> None:
    """Audit pilot-corpus helpers."""


@cli.command("build")
@click.option("--tag", default="audit_pilot_v1")
@click.option("--per-strategy", default=120, type=int)
@click.option("--seed", default=42, type=int)
@click.option(
    "--skip",
    multiple=True,
    type=click.Choice(list(STRATEGY_MODULES)),
    help="Skip one or more strategies",
)
@click.option(
    "--per-country-cap",
    type=float,
    default=None,
    help=(
        "Per-call absolute country cap (fraction in (0, 1]) forwarded to "
        "every strategy subprocess. Phase 2g.8 wire-up: previously the "
        "sampler accepted this kwarg but the orchestrator never passed it, "
        "so audit_pilot_v6 ran with NO cap (D3 = 4.52). Pass 0.10 for "
        "audit pilots; default unset (no cap)."
    ),
)
def build_cmd(
    tag: str, per_strategy: int, seed: int,
    skip: tuple[str, ...], per_country_cap: float | None,
) -> None:
    summary = build_pilot_corpus(
        tag=tag,
        per_strategy=per_strategy,
        seed=seed,
        skip_strategies=skip,
        per_country_cap=per_country_cap,
    )
    click.echo(f"Corpus tag: {summary['tag']}")
    click.echo(f"Totals by strategy: {summary['totals']}")


@cli.command("export-gold")
@click.option("--tag", default="audit_pilot_v1")
@click.option("--out", type=click.Path(), default="data/reports/gold_sheet.csv")
@click.option("--size", default=60, type=int)
@click.option("--seed", default=42, type=int)
def export_gold_cmd(tag: str, out: str, size: int, seed: int) -> None:
    count = export_gold_sheet(tag, Path(out), size, seed)
    click.echo(f"Wrote {count} rows to {out}")


@cli.command("import-gold")
@click.option("--csv-path", type=click.Path(exists=True), required=True)
@click.option("--reviewer", required=True, help="Reviewer identifier (e.g. 'nikita')")
def import_gold_cmd(csv_path: str, reviewer: str) -> None:
    count = import_gold_sheet(Path(csv_path), reviewer)
    click.echo(f"Imported {count} gold labels")


if __name__ == "__main__":
    cli()
