mindmap
    root((OenoBench\nData Sources))
        Knowledge Bases
            Wikidata SPARQL
                Country-scoped queries P17
                Direct location P131
                Wine region entities
                Grape variety entities
        Encyclopedias
            Wikipedia MediaWiki API
                Key article extracts
                Category tree crawls
                Infobox field parsing
                Wikitext table parsing
        Official Wine Bodies
            French
                CIVB Bordeaux
                BIVB Burgundy
                Inter-Rhone
                Vins de Loire
            European
                Austrian Wine
                German Wines DWI
                Wines of Portugal
                Spanish Wine MAPA
            New World
                Wine Australia
                NZ Wine
                WOSA South Africa
                Wines of Argentina
        Government Registries
            INAO data.gouv.fr
            TTB gov
            eCFR
            eAmbrosia EU GI
        Academic Sources
            OENO One journal
            AJEV journal
            Vitis journal
            UC Davis
            UC IPM
            Extension services
        Datasets
            HuggingFace
            Kaggle
            OIV reports
